### ISSUE TITLE
Handling of content type

### ISSUE THREAD

**Issue by errordeveloper** [binocarlos/powerstrip-weave#9]
After setting it all up according to the blog post, I ran this:
```
CID=$(docker run -e "WEAVE_CIDR=10.255.0.51/8" -d busybox)
```
and got:
```
server listening on port: 80

undefined:1
No such image: busybox
^
SyntaxError: Unexpected token N
    at Object.parse (native)
    at /srv/app/actions/create.js:47:26
    at /srv/app/dockerclient.js:15:7
    at ConcatStream.<anonymous> (/srv/app/node_modules/concat-stream/index.js:32:43)
    at ConcatStream.emit (events.js:117:20)
    at finishMaybe (/srv/app/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at afterWrite (/srv/app/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:340:3)
    at /srv/app/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:327:9
    at process._tickCallback (node.js:442:13)
```

**Comment by errordeveloper** [comment]
@binocarlos should this be closed?

**Comment by binocarlos** [comment]
yup although I was waiting until I fixed it properly (as in checking for the content-type rather than scan the body for the string "no image found")

**Comment by binocarlos** [comment]
Am doing this by checking the content-type headers now so am closing....
